### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by 18steps** [rubenCodeforges/angular2-google-api#1]
Following your example, I have
````
NgModule({
  ...
  imports: [
    ...
    GoogleApiModule.setConfig(
      new GoogleApiConfig(
        CLIENT_ID, DISCOVERY_DOCS, SCOPE
      )
    ),
  ],
  ...
})
export class AppModule { }
````

But when running `ng serve` I get an error from Webpack:

> ERROR in Error encountered resolving symbol values statically. Calling function 'GoogleApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ...

And in the browser console I get this error:

````
Uncaught Error: Can't resolve all parameters for factory: ([object Object], ?).
    at syntaxError (http://localhost:4200/vendor.bundle.js:36507:34)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:49844:35)
    at CompileMetadataResolver._getFactoryMetadata (http://localhost:4200/vendor.bundle.js:49724:51)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:49996:43)
    at http://localhost:4200/vendor.bundle.js:49917:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:49878:19)
    at http://localhost:4200/vendor.bundle.js:49453:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:49444:49)
````

**Comment by rubenCodeforges** [comment]
Hi have you replaced CLIENT_ID, DISCOVERY_DOCS, SCOPE with yours ?
Could you share perhaps the code ?

**Comment by rubenCodeforges** [comment]
In any case ill be back in the evening , will check it

**Comment by 18steps** [comment]
I actually meant the example in `README.md`, but let's talk about the example project you have, because I've tried it now and I get the same error

> ERROR in Error encountered resolving symbol values statically. Calling function 'GoogleApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppCommonModule in c:/dev/ng-gapi-example/src/app/common/AppCommonModule.ts, resolving symbol AppCommonModule in c:/dev/ng-gapi-example/src/app/common/AppCommonModule.ts

> ERROR in ./src/app/common/AppCommonModule.ts
Module not found: Error: Can't resolve './google/GoogleAuthService' in 'c:\dev\coop\ng-gapi-example\src\app\common'
 @ ./src/app/common/AppCommonModule.ts 15:0-63
 @ ./src/app/AppModules.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
webpack: Compiling...
Hash: 890bca36a3beb55b635e
Time: 3219ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 78.9 kB {3} [initial]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 525 kB {4} [initial]
chunk    {2} scripts.bundle.js, scripts.bundle.js.map (scripts) 2.93 MB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.27 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry]

> ERROR in ./src/app/common/AppCommonModule.ts
Module not found: Error: Can't resolve './google/GoogleAuthService' in 'c:\dev\coop\ng-gapi-example\src\app\common'
 @ ./src/app/common/AppCommonModule.ts 15:0-63
 @ ./src/app/AppModules.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by rubenCodeforges** [comment]
@18steps found the issue , working on a fix, will provide a fix together with the example , i guess today

**Comment by rubenCodeforges** [comment]
closed by https://github.com/rubenCodeforges/angular2-google-api/tree/bugfix/static-method-not-supported-in-module-config

**Comment by rubenCodeforges** [comment]
@18steps ive fixed the issue , ill make some test and then release new version

**Comment by rubenCodeforges** [comment]
@18steps the new version is live , please update your npm package, the latest version is 0.0.38
Also check the updated README , the configuration object has changed.

To avoid any caches , remove ng-gapi folder from node-modules, remove ng-gapi entry from package.json and then 

``` npm install ng-gapi --save```

**Comment by 18steps** [comment]
Thanks. I updated the package according to your instructions, but I still have errors.

In order to use the config type definitions in my module I updated `ng-gapi\lib\GoogleApiModule.ts` to also `export { GapiInitConfigs };`.

I got `no provider found for [object Object]` errors, so in my module I am providing GoogleApiService, GoogleApiConfig, GoogleAuthService. (AFAIK you chould import and export these so I get them automatically when I import GoogleApiModule)

Still now I have an error
> Can't resolve all parameters for GoogleApiConfig

My AppModule code is
````
const gapiConfig = { scope: ..., discoveryDocs: ..., clientId: ... };
...
  imports: [
    ....
    GoogleApiModule.setConfig(gapiConfig),
  ],
  providers: [
    GoogleApiService,
    GoogleApiConfig,
    GoogleAuthService,
    ...
  ],
````

**Comment by rubenCodeforges** [comment]
Hi ive made small adjustment , please update to new version.
Also don provide the libs services , its done inside the lib.
Just try again whats in the README and you should be fine 

Latest version 0.0.39

**Comment by 18steps** [comment]
Now it works better, thanks. But when I try to use the `gapi` object it errors. I'm trying to follow [the Reporting API example](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js)

When I call `gapi.client.request(...)` I get
> TypeError: Cannot read property 'request' of undefined

since there is no `client` property on the `gapi` object.

I guess it works in their example because they do
````html
<!-- Load the JavaScript API client and Sign-in library. -->
<script src="https://apis.google.com/js/client:platform.js"></script>
````
Any chance your library could support `gapi.client`?

**Comment by rubenCodeforges** [comment]
@18steps this relates to #2 ill finish the example and will ping you in that issue
