### ISSUE TITLE
Configuring gapi.auth2.ClientConfig

### ISSUE THREAD

**Issue by bxboxer219** [rubenCodeforges/angular2-google-api#11]
Hi Ruben(@rubenCodeforges),

First off, thanks for all of your work on this package.

I'm working on an app that is based on your reporting example.

Currently, the app works well, and I am able to sign in the user with their Google account. However, I would like for the oAuth dialog box to be redirected to (at Sign In), instead of popping up in a new tab.

I noticed that in the JS client library, Google mentions the [gapi.auth2.ClientConfig](https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2clientconfig) interface for configuring parameters for gapi.auth2.init. Inside of this interface, I noticed ux_mode allows you to set the dialog box to either popup or redirect mode.

I tried adding ux_mode and redirect_uri settings into different parts of the app, but wasn't quite sure where to add these settings in, with regards to ng-gapi. Do you know if gapi.auth2.ClientConfig is able to be configured with ng-gapi, so that on sign in, the user is redirected to the oauth dialog box?

Any help is greatly appreciated.

Thanks for your time.

Sincerely,

Blaine H.

**Comment by rubenCodeforges** [comment]
I'll see what I can do when I'm back home maybe on 2-3 hours.

**Comment by rubenCodeforges** [comment]
@bxboxer219 i will add a new config param for that , it will take perhaps 1d - 2d as im occupied with work

**Comment by rubenCodeforges** [comment]
@bxboxer219 the npm package is updated with new changes , pease remove old version from node_modules and do a fresh install. new version is ng-gapi@0.0.42-1.

In that version you can provide all parameters in the `forRoot()` method.
See the interface ClientConfig.
Also pleas report back if it worked out for you and if did please star ;)

**Comment by bxboxer219** [comment]
Thanks Ruben! I'm out at lunch right now but will update my project whenever I get home.

I've starred the project, and will be sure to update this thread after I adjust my code.

Thanks for everything :)

**Comment by bxboxer219** [comment]
I updated ng-gapi and the gapiClientConfig, and everything is working perfectly.

Thanks again for being so responsive, and for adding this enhancement so quick @rubenCodeforges

**Comment by rubenCodeforges** [comment]
@bxboxer219 you are welcome
