### ISSUE TITLE
Error en la compilacion

### ISSUE THREAD

**Issue by rojasjuniore** [rubenCodeforges/angular2-google-api#15]
ERROR in /home/junior/proyectos/A_proyecto-emiteme/emiteme-frontend/node_modules/@types/gapi/index.d.ts (243,37): ',' expected.

**Comment by bxboxer219** [comment]
@rojasjuniore try updating typescript.

npm install --save typescript@latest

**Comment by rubenCodeforges** [comment]
@rojasjuniore you need to update to latest ts version as @bxboxer219 mentioned

**Comment by rojasjuniore** [comment]
Gracias.
