### ISSUE TITLE
Login fails with error > err = {error: "popup_closed_by_user"}

### ISSUE THREAD

**Issue by MikeHibbert** [rubenCodeforges/angular2-google-api#16]
After setting up and running with my own client id I go through the login process and select the needed google account in the popup.

Once this has been selected the login fails with the error in the console being:

err = {error: "popup_closed_by_user"}

from line 34 of UserService.ts which uses the error handler for signin

Any idea how to fix this?

**Comment by rubenCodeforges** [comment]
Hi , @MikeHibbert did you used my example project ?

**Comment by MikeHibbert** [comment]
Hi @rubenCodeforges 

Yes, you were right! AdBlocker was the culprit!

**Comment by rubenCodeforges** [comment]
@MikeHibbert here you go ;)

**Comment by vitto-moz** [comment]
I faced an interesting question - how can I handle this error - can't catch it - it seems it occurs in no Angluar environment

**Comment by rubenCodeforges** [comment]
@vitto-moz what error ?

**Comment by vitto-moz** [comment]
I'm sorry, it seems screenshot was not attached 
here it is 
![image](https://user-images.githubusercontent.com/19843391/37525054-5fe9649c-2934-11e8-8e39-250bee0b5ded.png)

**Comment by rubenCodeforges** [comment]
@vitto-moz hard to say what you are doing but i guess you are calling auth.signIn();

In this case you here is an example: 
`auth.signIn().then(res => this.signInSuccessHandler(res), err => this.signInErrorHandler(err));`

as signIn returns a promise the first callback is a success handler and the second a error handler.
In your case closing the popup calls the error handler.

Now to Angular , you are correct the handlers are outside Angular zone , so you just need to use `ngZone` inside the callback and just run the angular code.

Here is a example from my example project: 
https://github.com/rubenCodeforges/ng-gapi/blob/feature/example-project/examples/src/app/common/user/UserService.ts

see how `signInSuccessHandler` is working with ngZone
