### ISSUE TITLE
NgGapiClientConfig missing and ClientConfig doesn't have a client_id field

### ISSUE THREAD

**Issue by rigolepe** [rubenCodeforges/angular2-google-api#20]
Your README mentions a`NgGapiClientConfig`, which is absent in your npm library. There is a `ClientConfig` class that has a field `clientId`, which should be `client_id` instead.

**Comment by rigolepe** [comment]
Never mind, I was still on version 0.0.42-1, the class inconsistency seems to be gone there, although I still hit `Missing required parameter 'client_id'` even though the parameter is there.

**Comment by rubenCodeforges** [comment]
Show me your mode file where the configuration is .

**Comment by rigolepe** [comment]
I got it to work. My confusion was that I thought I could use `gapi.signin2` or `gapi.auth2` in the following block: 

```
        gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi
        });
```

Then I studied your implementation and I figured that I had to do this:

```
    this.googleAuthService.getAuth().subscribe(googleAuth => {
      // use gapi.signin2 
    })
```

Nice project by the way!

**Comment by rubenCodeforges** [comment]
@rigolepe Thanks you .
Btw the onLoad method is successful when the module has added the script tag and the script is loaded.
So after it is done , then you can use gapi.
