### ISSUE TITLE
Issue in production mode

### ISSUE THREAD

**Issue by iderets** [rubenCodeforges/angular2-google-api#4]
Hello.

I'm starting using your lib in my project. And everything is working fine once in dev mode (`ng serve`) but when it goes to production (`ng build -prod`) I get the error:

```ERROR TypeError: Cannot read property 'clientId' of undefined```

Raised from minified version of

```
function GoogleApiConfig(configs) {
        this.CLIENT_ID = configs.clientId;
        this.DISCOVERY_DOCS = configs.discoveryDocs;
        this.SCOPE = configs.scope;
    }
```
```
My Implementation:
@NgModule({
  imports: [
    CommonModule,
    AuthRoutingModule,
    FormsModule,
    GoogleApiModule.setConfig({
      clientId: environment.socialAuth.google.clientId,
      discoveryDocs: [''],
      scope: ""
    })
  ],
...
})
```

**Comment by iderets** [comment]
Looks like in production mode setConfig is not called

**Comment by rubenCodeforges** [comment]
@iderets hi , thanks for using the lib.
Can you tell me please the following:
1. Are you using the lib from npm ?
2. can you see if it runs with `ng build --prod --aot` ?

**Comment by rubenCodeforges** [comment]
@iderets otherwise you can reach me out via skype: eldar2ndpara

**Comment by iderets** [comment]
Hi @rubenCodeforges , thank you for quick response:
1. Yes from npm (0.39)
2. --aot didn't help

**Comment by rubenCodeforges** [comment]
@iderets is 
`function GoogleApiConfig(configs)` configs undefined ?

**Comment by iderets** [comment]
no, config argument is undefined. I've done some debug. and what I've found:
in prod mode .setConfig() is not called at all. So when the new instance of GoogleApiService created - there is no apiConfig defined

**Comment by iderets** [comment]
So the issue that static method GoogleApiModule.setConfig is never called

**Comment by rubenCodeforges** [comment]
@iderets what angular version ?
