### ISSUE TITLE
Client apis not loaded

### ISSUE THREAD

**Issue by zorgoz** [rubenCodeforges/angular2-google-api#7]
Hello,
I might be totally wrong, but I can't get GoogleApiService working. Authentication is ok. I have correct configuration. Still, when I step into gapiService.onLoad callback based on your usage pattern, there is no `gapi.client`, even less `gapi.client.drive` defined in window object.
I have a non-ng JavaScript version, that works...

How to proceed? Thank you.

**Comment by rubenCodeforges** [comment]
did you used the npm version ?

**Comment by rubenCodeforges** [comment]
@zorgoz if you do use npm version , then its see #4 the pr #6 will fix it, currently im testing the npm build, if its ok ill make a new release

**Comment by zorgoz** [comment]
Yes, I am using the npm version. I am looking ahead for the upgrade.

**Comment by rubenCodeforges** [comment]
@zorgoz all done , new version `0.0.41 ` please update

issue related to #4

**Comment by rubenCodeforges** [comment]
@zorgoz btw checkout new configuration in the docs

**Comment by zorgoz** [comment]
Hello! Thank you for the enhancements. Sorry, I have not reacted, but this project was suspended for some time. 
I still have problems. I am trying to follow your configuration instructions. With `import { ClientConfig, GoogleApiModule } from 'ng-gapi';` I can declare the configuration, but 

> GoogleApiModule.forRoot({
>             provide: NG_GAPI_CONFIG,
>             useValue: gapiClientConfig
>           }),
is failing, as I can't get NG_GAPI_CONFIG in my code. Your sample importing it with `import {NG_GAPI_CONFIG} from "../../src/GoogleApiService";`, but how to get it from the npm package?

Thank you,

**Comment by rubenCodeforges** [comment]
Hi first for all dont import by hand , your IDE should handle it , use the jet brains ide ( webstorm, intellij) 
If you still cant do it with IDE , you need to import from node_modules/ng-gapi/lib

**Comment by zorgoz** [comment]
I am using VSCode. I could not compile without adding `import { NG_GAPI_CONFIG } from '../../node_modules/ng-gapi/lib/GoogleApiService';`.

**Comment by rubenCodeforges** [comment]
Without imort it will not work but IDE does import for you. I guess VS is
just bad for Web app development. I prefer intellij

**Comment by rubenCodeforges** [comment]
@zorgoz did it solved your issue ? Can i close the issue ?

**Comment by rubenCodeforges** [comment]
@zorgoz btw ive got an open issue for a working example , see #13 perhaps in 2 days ill deploy it

**Comment by zorgoz** [comment]
Actually not. I'l wait to see this. Thank you.

**Comment by jasonc624** [comment]
Hi, so will this work for Google Places api?

**Comment by rubenCodeforges** [comment]
@jasonc624 why not )

**Comment by rubenCodeforges** [comment]
@zorgoz the example is complete , see it here https://github.com/rubenCodeforges/angular2-google-api/tree/master/examples
